function Place(place, displayName){
	this.place = place;
	this.displayName = displayName;
};

var places = [];

places.push(new Place ('accounting', 'Accountant'));
places.push(new Place ('airport', 'Airport'));
places.push(new Place ('amusement_park', 'Amusement park'));
places.push(new Place ('aquarium', 'Aquarium'));
places.push(new Place ('art_gallery', 'Art gallery'));
places.push(new Place ('atm', 'ATM'));
places.push(new Place ('bakery', 'Bakery'));
places.push(new Place ('bank', 'Bank'));
places.push(new Place ('bar', 'Bar'));
places.push(new Place ('beauty_salon', 'Beauty Salon'));
places.push(new Place ('bicycle_store', 'Bicycle Store'));
places.push(new Place ('book_store', 'Book Store'));
places.push(new Place ('bowling_alley', 'Bowling Alley'));
places.push(new Place ('bus_station', 'Bus Station'));
places.push(new Place ('cafe', 'Cafe'));
places.push(new Place ('campground', 'Campground'));
places.push(new Place ('car_dealer', 'Car Dealer'));
places.push(new Place ('car_rental', 'Car Rental'));
places.push(new Place ('car_repair', 'Car Repair'));
places.push(new Place ('car_wash', 'Car Wash'));
places.push(new Place ('casino', 'Casino'));
places.push(new Place ('cemetery', 'Cemetery'));
places.push(new Place ('church', 'Church'));
places.push(new Place ('city_hall', 'City Hall'));
places.push(new Place ('clothing_store', 'Clothing Store'));
places.push(new Place ('convenience_store', 'Convenience Store'));
places.push(new Place ('courthouse', 'Courthouse'));
places.push(new Place ('dentist', 'Dentist'));
places.push(new Place ('department_store', 'Department Store'));
places.push(new Place ('doctor', 'Doctor'));
places.push(new Place ('electrician', 'Electrician'));
places.push(new Place ('electronics_store', 'Electronics Store'));
places.push(new Place ('embassy', 'Embassy'));
places.push(new Place ('fire_station', 'Fire Station'));
places.push(new Place ('florist', 'Florist'));
places.push(new Place ('funeral_home', 'Funeral Home'));
places.push(new Place ('furniture_store', 'Furniture Store'));
places.push(new Place ('gas_station', 'Gas Station'));
places.push(new Place ('grocery_or_supermarket', 'Grocery or Supermarket'));
places.push(new Place ('gym', 'Gym'));
places.push(new Place ('hair_care', 'Hair Care'));
places.push(new Place ('hardware_store', 'Hardware Store'));
places.push(new Place ('hindu_temple', 'Hindu Temple'));
places.push(new Place ('home_goods_store', 'Home Goods Store'));
places.push(new Place ('hospital', 'Hospital'));
places.push(new Place ('insurance_agency', 'Insurance Agency'));
places.push(new Place ('jewelry_store', 'Jewelry Store'));
places.push(new Place ('laundry', 'Laundry'));
places.push(new Place ('lawyer', 'Lawyer'));
places.push(new Place ('library', 'Library'));
places.push(new Place ('liquor_store', 'Liquor Store'));
places.push(new Place ('local_government_office', 'Local Government Office'));
places.push(new Place ('locksmith', 'Locksmith'));
places.push(new Place ('lodging', 'Lodging'));
places.push(new Place ('meal_delivery', 'Meal Delivery'));
places.push(new Place ('meal_takeaway', 'Meal Takeaway'));
places.push(new Place ('mosque', 'Mosque'));
places.push(new Place ('movie_rental', 'Movie Rental'));
places.push(new Place ('movie_theater', 'Movie Theater'));
places.push(new Place ('moving_company', 'Moving Company'));
places.push(new Place ('museum', 'Museum'));
places.push(new Place ('night_club', 'Night_ Club'));
places.push(new Place ('painter', 'Painter'));
places.push(new Place ('park', 'park'));
places.push(new Place ('parking', 'Parking'));
places.push(new Place ('pet_store', 'Pet Store'));
places.push(new Place ('pharmacy', 'Pharmacy'));
places.push(new Place ('physiotherapist', 'Physiotherapist'));
places.push(new Place ('plumber', 'Plumber'));
places.push(new Place ('police', 'Police'));
places.push(new Place ('post_office', 'Post Office'));
places.push(new Place ('real_estate_agency', 'Real Estate Agency'));
places.push(new Place ('restaurant', 'Restaurant'));
places.push(new Place ('roofing_contractor', 'Roofing Contractor'));
places.push(new Place ('rv_park', 'RV Park'));
places.push(new Place ('school', 'School'));
places.push(new Place ('shoe_store', 'Shoe Store'));
places.push(new Place ('shopping_mall', 'Shopping Mall'));
places.push(new Place ('spa', 'Spa'));
places.push(new Place ('stadium', 'Stadium'));
places.push(new Place ('storage', 'Storage'));
places.push(new Place ('store', 'Store'));
places.push(new Place ('subway_station', 'Subway Station'));
places.push(new Place ('synagogue', 'Synagogue'));
places.push(new Place ('taxi_stand', 'Taxi Stand'));
places.push(new Place ('train_station', 'Train Station'));
places.push(new Place ('transit_station', 'Transit Station'));
places.push(new Place ('travel_agency', 'Travel Agency'));
places.push(new Place ('university', 'University'));
places.push(new Place ('veterinary_care', 'Veterinary Care'));
places.push(new Place ('zoo', 'Zoo'));


